name: Crawl directories, maps, and newsletters webpages and deploy to main branch

on:
  schedule:
    - cron: "30 21 * * *" # 每天 05:30 (GMT+8) 執行，因為 GitHub Actions 使用 UTC 時間 (21:30 UTC = 05:30 GMT+8)
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ["self-hosted", "ARM64", "Linux"]
    env:
      TZ: Asia/Taipei
      DATA_FOLDER: data
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python crawler
        run: |
          python scripts/directories.py || true
          python scripts/maps.py || true
          python scripts/newsletters.py || true

      - name: Update Data in main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add $DATA_FOLDER
          if ! git diff-index --quiet HEAD --; then
            git commit -m "📝 Scheduled update of JSON data"
            git push
          else
            echo "No changes to commit."
          fi
