name: Scheduled update of JSON data in gh-pages

on:
  schedule:
    - cron: '0 * * * *'  # 每小時的第 0 分鐘執行

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Run Python update script
        run: |
            # 執行 buses.py 與 dining.py，若失敗不會中斷流程（加上 || true）
            python scripts/buses.py || true
            python scripts/dining.py || true

            # 有些爬蟲無法順利執行，先註解掉（學校好像有擋國外 IP）
            # python scripts/directories.py || true
            # python scripts/maps.py || true
            # python scripts/newsletters.py || true

            python scripts/courses.py || true

      - name: Copy updated JSON files to docs folder
        run: |
          mkdir -p docs
          cp -r json/* docs/

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Scheduled update of JSON data [skip ci] - $(date)"
            git push origin gh-pages
          else
            echo "No changes to commit."
          fi